In [51]:
import numpy as np

In [ ]:
simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
lists_of_lists=([1,2,3],[4,5,6],[6,7,8])
np.array(lists_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.arange(5,25)

TypeError: ignored

In [44]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [46]:
np.random.rand(2,4)

array([[0.38955908, 0.07425715, 0.09991781, 0.65953105],
       [0.90514448, 0.76771735, 0.05419839, 0.76854027]])

In [47]:
np.random.randn(2,4)

array([[-0.07294788,  0.2355147 , -0.9362429 , -1.23425968],
       [-0.57425835,  1.62941262,  1.10440827, -1.01368567]])

In [48]:
np.random.randint(2,4)

3

In [49]:
np.random.randint(20,56,100)

array([20, 24, 24, 20, 36, 25, 32, 31, 40, 54, 20, 43, 30, 20, 31, 28, 35,
       48, 48, 43, 30, 41, 27, 22, 31, 54, 34, 55, 32, 29, 23, 54, 40, 31,
       40, 42, 50, 44, 23, 23, 32, 25, 33, 26, 27, 26, 40, 38, 22, 36, 37,
       55, 23, 27, 47, 37, 50, 22, 31, 25, 48, 48, 44, 27, 20, 31, 51, 37,
       50, 33, 47, 40, 25, 27, 47, 42, 23, 55, 32, 36, 43, 32, 45, 55, 44,
       38, 45, 31, 26, 32, 41, 55, 48, 29, 26, 52, 35, 35, 22, 47])